{
  "collapse-filter": false,
  "search": "path:\"wiki\"",
  "showTags": false,
  "showAttachments": false,
  "hideUnresolved": true,
  "showOrphans": false,
  "collapse-color-groups": true,
  "colorGroups": [],
  "collapse-display": false,
  "showArrow": true,
  "textFadeMultiplier": 0,
  "nodeSizeMultiplier": 1.2,
  "lineSizeMultiplier": 1.1,
  "collapse-forces": true,
  "centerStrength": 0.52,
  "repelStrength": 12,
  "linkStrength": 1,
  "linkDistance": 220,
  "scale": 1,
  "close": false
}
